-- pgbench script: Rule repository save operations
-- This tests concurrent rule saves with versioning

\set rule_id random(1, 100000)
\set threshold random(1, 1000)
\set discount_pct random(1, 50)

SELECT rule_save(
    format('test_rule_%s', :rule_id),
    format('rule "TestRule_%s" { when Order.total > %s then Order.discount = %s; }',
        :rule_id,
        50 + (:threshold % 500),
        0.05 + ((:discount_pct % 20) * 0.01)
    ),
    NULL,  -- Auto version
    format('Test rule %s for load testing', :rule_id),
    'Generated by load test'
);
